apiVersion: v1
kind: Secret
metadata:
  name: dia-secrets
  namespace: dia-system
  labels:
    app.kubernetes.io/name: data-intelligence-assistant
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: dia-platform
type: Opaque
stringData:
  DIA_JWT_SECRET: "dia-prod-super-secure-jwt-signing-key-minimum-32-chars"
  DIA_API_KEYS: '{"dia-admin-prod-key":{"role":"Admin","tenant_id":"enterprise","org_id":"hq","user_id":"secops-admin"},"dia-ds-prod-key":{"role":"DataScientist","tenant_id":"enterprise","org_id":"hq","user_id":"lead-ds"},"dia-auditor-prod-key":{"role":"Auditor","tenant_id":"enterprise","org_id":"hq","user_id":"compliance-officer"},"dia-viewer-prod-key":{"role":"Viewer","tenant_id":"enterprise","org_id":"hq","user_id":"executive-viewer"}}'
  DIA_S3_ACCESS_KEY_ID: "CHANGE_ME_S3_ACCESS_KEY"
  DIA_S3_SECRET_ACCESS_KEY: "CHANGE_ME_S3_SECRET_KEY"
  DIA_GROQ_API_KEY: ""
  DIA_GEMINI_API_KEY: ""
