"""
dia/feature_store.py
────────────────────
Automated Feature Store & Point-in-Time Correctness Engine.
Generates Feast-compatible feature definitions, feature views, entity keys,
and performs point-in-time joins to guarantee zero temporal data leakage.
"""

from __future__ import annotations

import logging
from typing import Any

import pandas as pd

log = logging.getLogger("dia.feature_store")


def generate_feature_store_definitions(
    df: pd.DataFrame,
    entity_col: str,
    target_col: str,
    feature_view_name: str = "customer_features_fv",
    ttl_days: int = 30,
) -> dict[str, Any]:
    """
    Analyzes DataFrame schema and generates a Feast-compatible feature definition schema
    with Entity, FeatureView, Field types, and source batch configs.
    """
    feature_cols = [c for c in df.columns if c not in [entity_col, target_col]]

    schema_fields = []
    for c in feature_cols:
        dtype_str = str(df[c].dtype)
        if "int" in dtype_str:
            feast_type = "Int64"
        elif "float" in dtype_str:
            feast_type = "Float64"
        elif "bool" in dtype_str:
            feast_type = "Bool"
        elif "datetime" in dtype_str:
            feast_type = "UnixTimestamp"
        else:
            feast_type = "String"
        schema_fields.append({"name": c, "feast_type": feast_type, "source_dtype": dtype_str})

    # Generate Feast Python Definition Code
    fields_py = "\n".join([f'        Field(name="{f["name"]}", dtype={f["feast_type"]}),' for f in schema_fields])

    feast_python_code = f"""# Feast Feature Store Definitions (Generated by DIA v10.0)
from datetime import timedelta
from feast import (
    Entity,
    FeatureView,
    Field,
    FileSource,
    ValueType,
)
from feast.types import Float64, Int64, String, Bool, UnixTimestamp

# 1. Define Entity Key
entity = Entity(
    name="{entity_col}",
    join_keys=["{entity_col}"],
    description="Primary entity identifier for point-in-time lookups",
)

# 2. Define Batch File Source
batch_source = FileSource(
    name="{feature_view_name}_source",
    path="data/{feature_view_name}.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp",
)

# 3. Define Feature View with TTL
{feature_view_name} = FeatureView(
    name="{feature_view_name}",
    entities=[entity],
    ttl=timedelta(days={ttl_days}),
    schema=[
{fields_py}
    ],
    online=True,
    source=batch_source,
    tags={{"team": "mlops", "version": "v1.0"}},
)
"""

    # Generate Feast feature_store.yaml
    feast_yaml_code = """project: dia_enterprise_feature_store
registry: data/registry.db
provider: local
online_store:
    type: sqlite
    path: data/online_store.db
offline_store:
    type: file
"""

    return {
        "status": "success",
        "entity_key": entity_col,
        "feature_view_name": feature_view_name,
        "ttl_days": ttl_days,
        "total_features_registered": len(feature_cols),
        "schema_fields": schema_fields,
        "feast_python_code": feast_python_code,
        "feast_yaml_code": feast_yaml_code,
    }


def perform_point_in_time_join(
    events_df: pd.DataFrame,
    features_df: pd.DataFrame,
    entity_col: str,
    event_timestamp_col: str,
    feature_timestamp_col: str,
) -> pd.DataFrame:
    """
    Executes a Point-in-Time (ASOF) join between observation events and historical feature snapshots.
    Guarantees that observations only join with feature rows whose feature_timestamp <= event_timestamp.
    """
    events_sorted = events_df.sort_values(event_timestamp_col)
    features_sorted = features_df.sort_values(feature_timestamp_col)

    joined = pd.merge_asof(
        events_sorted,
        features_sorted,
        by=entity_col,
        left_on=event_timestamp_col,
        right_on=feature_timestamp_col,
        direction="backward",
    )
    return joined
